### Red neuronal para predecir el ganador de un duelo en el juego League ogf Legends

In [2]:
import numpy as np
import pandas as pd
import sklearn

In [3]:
data = pd.read_csv("games.csv", sep=";")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50286 entries, 0 to 50285
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gameDuration        50286 non-null  int64
 1   firstBlood          50286 non-null  int64
 2   firstTower          50286 non-null  int64
 3   firstInhibitor      50286 non-null  int64
 4   firstBaron          50286 non-null  int64
 5   firstDragon         50286 non-null  int64
 6   firstRiftHerald     50286 non-null  int64
 7   t1_towerKills       50286 non-null  int64
 8   t1_inhibitorKills   50286 non-null  int64
 9   t1_baronKills       50286 non-null  int64
 10  t1_dragonKills      50286 non-null  int64
 11  t1_riftHeraldKills  50286 non-null  int64
 12  t2_towerKills       50286 non-null  int64
 13  t2_inhibitorKills   50286 non-null  int64
 14  t2_baronKills       50286 non-null  int64
 15  t2_dragonKills      50286 non-null  int64
 16  t2_riftHeraldKills  50286 non-null  int6

In [4]:
data.head(30)

gameDuration  firstBlood  firstTower  firstInhibitor  firstBaron  \
0           1949           2           1               1           1   
1           1851           1           1               1           0   
2           1493           2           1               1           1   
3           1758           1           1               1           1   
4           2094           2           1               1           1   
5           2059           2           2               1           1   
6           1993           1           2               1           1   
7           1334           1           1               0           0   
8           1387           2           2               2           0   
9           2681           2           2               2           2   
10          1391           2           2               2           2   
11          1671           1           2               1           0   
12          2071           1           1               0           1   
13          1942           2           2               1           0   
14          2374           2           2               1           1   
15          1717           2           1               1           0   
16          2390           2           2               2           2   
17          1994           2           1               1           1   
18          1513           1           2               2           0   
19          1898           1           2               2           2   
20          2026           1           1               1           2   
21          1962           1           2               2           2   
22          1511           1           2               2           0   
23          1756           1           1               1           1   
24          2173           2           2               2           0   
25          2211           2           2               2           0   
26          2472           2           2               1           1   
27          1342           2           2               0           0   
28          2288           1           2               2           2   
29          1899           1           1               1           1   

    firstDragon  firstRiftHerald  t1_towerKills  t1_inhibitorKills  \
0             1                2             11                  1   
1             1                1             10                  4   
2             2                0              8                  1   
3             1                0              9                  2   
4             1                0              9                  2   
5             2                0              8                  1   
6             1                1             10                  2   
7             2                1              6                  0   
8             2                2              0                  0   
9             2                0             10                  1   
10            2                2              0                  0   
11            2                1             10                  1   
12            2                1              6                  0   
13            1                0              7                  1   
14            2                0              8                  1   
15            1                0              7                  1   
16            2                0              3                  0   
17            1                1             11                  6   
18            2                0              0                  0   
19            1                1              4                  0   
20            1                2              5                  1   
21            1                0              2                  0   
22            2                0              2                  0   
23            1                1             11                  3   
24            1      

# Se hace una descripción estadistica

In [5]:
data.describe()

gameDuration    firstBlood    firstTower  firstInhibitor    firstBaron  \
count  50286.000000  50286.000000  50286.000000    50286.000000  50286.000000   
mean    1871.386032      1.487233      1.485125        1.339578      0.948693   
std      450.876052      0.499842      0.500499        0.652960      0.838988   
min      610.000000      1.000000      0.000000        0.000000      0.000000   
25%     1554.000000      1.000000      1.000000        1.000000      0.000000   
50%     1846.000000      1.000000      1.000000        1.000000      1.000000   
75%     2156.750000      2.000000      2.000000        2.000000      2.000000   
max     4728.000000      2.000000      2.000000        2.000000      2.000000   

        firstDragon  firstRiftHerald  t1_towerKills  t1_inhibitorKills  \
count  50286.000000     50286.000000   50286.000000       50286.000000   
mean       1.477270         0.749195       5.835163           1.041781   
std        0.530346         0.824393       3.740575           1.269064   
min        0.000000         0.000000       0.000000           0.000000   
25%        1.000000         0.000000       2.000000           0.000000   
50%        1.000000         1.000000       6.000000           1.000000   
75%        2.000000         1.000000       9.000000           2.000000   
max        2.000000         2.000000      11.000000          10.000000   

       t1_baronKills  t1_dragonKills  t1_riftHeraldKills  t2_towerKills  \
count   50286.000000    50286.000000        50286.000000   50286.000000   
mean        0.381200        1.420356            0.257487       5.681999   
std         0.588001        1.201740            0.437254       3.809336   
min         0.000000        0.000000            0.000000       0.000000   
25%         0.000000        0.000000            0.000000       2.000000   
50%         0.000000        1.000000            0.000000       6.000000   
75%         1.000000        2.000000            1.000000       9.000000   
max         5.000000        6.000000            1.000000      11.000000   

       t2_inhibitorKills  t2_baronKills  t2_dragonKills  t2_riftHeraldKills  \
count       50286.000000   50286.000000    50286.000000        50286.000000   
mean            1.008611       0.424472        1.437975            0.245854   
std             1.261867       0.617672        1.219412            0.430597   
min             0.000000       0.000000        0.000000            0.000000   
25%             0.000000       0.000000        0.000000            0.000000   
50%             0.000000       0.000000        1.000000            0.000000   
75%             2.000000       1.000000        2.000000            0.000000   
max            10.000000       4.000000        6.000000            1.000000   

             winner  
count  50286.000000  
mean       1.493776  
std        0.499966  
min        1.000000  
25%        1.000000  
50%        1.000000  
75%        2.000000  
max        2.000000

# Se separan los datos (80% de entrenamiento y 20% de prueba)

In [6]:
from sklearn.model_selection import train_test_split 
N=len(data)
cTrain=int(N*0.8) # 80% para entrenar y 20% para probar
cTest=N-cTrain
print(N,cTrain,cTest)
train_data,test_data= sklearn.model_selection.train_test_split(data, train_size=cTrain, test_size=cTest)

50286 40228 10058


In [7]:
train_data.shape

(40228, 18)

In [38]:
train_data.head(20)

gameDuration  firstBlood  firstTower  firstInhibitor  firstBaron  \
11971          2254           1           1               1           1   
6940           2368           2           2               2           2   
15376          2421           2           2               2           2   
5552           1851           1           1               2           2   
41098          1885           1           1               2           2   
17238          1830           1           2               2           2   
40065          2376           1           1               1           2   
16955          2024           1           2               1           1   
24783          2052           1           1               1           2   
25041          2865           1           2               1           1   
28879          2195           2           2               2           2   
12237          1632           2           1               2           0   
36446          2520           1           1               1           1   
19256          2063           2           1               1           2   
12856          1455           1           1               1           0   
26601          2274           1           1               1           0   
26771          2669           1           2               2           0   
33635          1498           1           1               2           0   
16159          1364           2           1               0           0   
33786          1407           2           2               2           0   

       firstDragon  firstRiftHerald  t1_towerKills  t1_inhibitorKills  \
11971            1                1             11                  6   
6940             1                0              4                  0   
15376            1                2              5                  0   
5552             2                2              3                  0   
41098            2                2              3                  0   
17238            2                0              2                  0   
40065            1                0              8                  3   
16955            2                0              9                  2   
24783            1                1             11                  4   
25041            2                0              6                  2   
28879            2                2              1                  0   
12237            2                0              2                  0   
36446            1                0             11                  3   
19256            2                1              9                  1   
12856            1                0              9                  2   
26601            2                2              8                  3   
26771            2                0              6                  0   
33635            2                0              2                  0   
16159            1                0              5                  0   
33786            2                1              1                  0   

       t1_baronKills  t1_dragonKills  t1_riftHeraldKills  t2_towerKills  \
11971              2               3                   1              2   
6940               0               1                   0             11   
15376              0               3                   0              9   
5552               0               0                   0             11   
41098              0               2                   0              9   
17238              0               1                   0             10   
40065              1               3                   0              9   
16955              1               2                   0              4   
24783              1               3                   1              4   
25041              1               1                   0             10   
28879              0               1                   0             11 

# Se hace un Pipeline para todos los atributos, teniendo en cuenta que todos son de tipo entero

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

num_attribs = ['gameDuration', 'firstBlood', 'firstTower', 'firstInhibitor', 'firstBaron', 'firstDragon', 'firstRiftHerald', 't1_towerKills', 't1_inhibitorKills', 't1_baronKills', 't1_dragonKills', 't1_riftHeraldKills', 't2_towerKills', 't2_inhibitorKills', 't2_baronKills', 't2_dragonKills', 't2_riftHeraldKills']
num_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()) 
    
    ])

In [10]:
from sklearn.compose import ColumnTransformer

full_pipeline = ColumnTransformer([
    ("num", num_pipeline, num_attribs),
])

In [11]:
X_train = full_pipeline.fit_transform(train_data)

X_train[0,:]

array([ 0.84467521, -0.97617126, -0.97137787, -0.5210236 ,  0.06019232,
       -0.89737297,  0.30227582,  1.38139002,  3.90756447,  2.75378023,
        1.30655243,  1.70214768, -0.96856769, -0.80102593, -0.68959952,
       -0.35792967, -0.57268102])

# Se estrae las etiquetas de clase

In [20]:
y_train = train_data['winner']
y_train

11971    1
6940     2
15376    2
5552     2
41098    2
        ..
34295    1
43529    1
46472    1
29800    1
27347    2
Name: winner, Length: 40228, dtype: int64

# Se crean las redes neuronales

In [21]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score

modelo1 = MLPClassifier(activation='logistic',solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(40, 50), random_state=123)
modelo1.fit(X_train, y_train)
scores1 = cross_val_score(modelo1, X_train, y_train, cv=5, scoring='accuracy')
print(scores1)
scores1.mean()

/Users/manuel/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/Users/manuel/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/Users/manuel/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to conv

[0.97601293 0.97725578 0.97477007 0.97638285 0.97712865]


/Users/manuel/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


0.9763100549713603

In [23]:
modelo2 = MLPClassifier(activation='identity',solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(16,4), random_state=123)
modelo2.fit(X_train, y_train)
scores2 = cross_val_score(modelo2, X_train, y_train, cv=5, scoring='accuracy')
print(scores2)
scores2.mean()

[0.97129008 0.97477007 0.96880437 0.97302672 0.97402113]


0.9723824769539103

In [24]:
modelo3 = MLPClassifier(activation='logistic',solver='sgd', alpha=1e-5,hidden_layer_sizes=(23,7), random_state=123)
modelo3.fit(X_train, y_train)
scores3 = cross_val_score(modelo3, X_train, y_train, cv=5, scoring='accuracy')
print(scores3)
scores3.mean()

/Users/manuel/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/manuel/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/manuel/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/manuel/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.9711658  0.97489436 0.97066866 0.97265382 0.97489124]


/Users/manuel/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


0.9728547736778286

In [25]:
modelo4 = MLPClassifier(activation='tanh',solver='sgd', alpha=1e-5,hidden_layer_sizes=(50,), random_state=123)
modelo4.fit(X_train, y_train)
scores4 = cross_val_score(modelo4, X_train, y_train, cv=5, scoring='accuracy')
print(scores4)
scores4.mean()

[0.97265722 0.97825006 0.97153865 0.97513984 0.97625855]


0.9747688639916502

In [26]:
modelo5 = MLPClassifier(activation='relu',solver='adam', alpha=1e-5,hidden_layer_sizes=(12,23), random_state=123)
modelo5.fit(X_train, y_train)
scores5 = cross_val_score(modelo5, X_train, y_train, cv=5, scoring='accuracy')
print(scores5)
scores5.mean()

[0.97862292 0.9813572  0.97825006 0.97973897 0.97837166]


/Users/manuel/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


0.979268160840858

In [27]:
X_test = full_pipeline.transform(test_data)
X_test

array([[-1.3634277 ,  1.02441041, -0.97137787, ..., -0.68959952,
        -1.17790659, -0.57268102],
       [-0.87175384, -0.97617126, -0.97137787, ..., -0.68959952,
        -1.17790659, -0.57268102],
       [-1.26376408,  1.02441041, -0.97137787, ..., -0.68959952,
        -1.17790659, -0.57268102],
       ...,
       [ 0.031863  ,  1.02441041,  1.02599429, ..., -0.68959952,
         0.46204725,  1.74617275],
       [-1.43429961, -0.97617126, -0.97137787, ..., -0.68959952,
        -0.35792967, -0.57268102],
       [-1.00020917,  1.02441041, -0.97137787, ..., -0.68959952,
        -0.35792967, -0.57268102]])

In [28]:
y_pred1 = modelo1.predict(X_test)  
y_pred1

array([1, 1, 1, ..., 2, 1, 1])

In [29]:
y_pred2 = modelo2.predict(X_test)  
y_pred2

array([1, 1, 1, ..., 2, 1, 1])

In [30]:
y_pred3 = modelo3.predict(X_test)  
y_pred3

array([1, 1, 1, ..., 2, 1, 1])

In [31]:
y_pred4 = modelo4.predict(X_test)  
y_pred4

array([1, 1, 1, ..., 2, 1, 1])

In [32]:
y_pred5 = modelo5.predict(X_test)  
y_pred5

array([1, 1, 1, ..., 2, 1, 1])

In [47]:
y_pred3[len(y_pred5)-5:len(y_pred5)]
y_pred3[:10]


array([1, 1, 1, 1, 1, 1, 2, 2, 2, 1])

In [48]:
y_test = test_data["winner"]
y_test[:10]

40623    1
33480    1
26405    1
25689    1
15241    1
42578    1
3608     2
9513     2
31419    2
17332    1
Name: winner, dtype: int64